# Generated by Django 4.0 on 2022-11-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_brand_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
